# Generated by Django 3.2.12 on 2023-10-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrishop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='isDelivered',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='placed', max_length=40),
        ),
    ]
